import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import newTheme from '../utils/Constants';
import {useNavigation} from '@react-navigation/native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Design from '../utils/Design';

const PrivacyPolicy = () => {
  const navigation = useNavigation();
  return (
    <ScrollView style={[Design.container,{padding: 10,}]}>
      <TouchableOpacity
        style={{height: 40, width: 40, bottom: 3}}
        onPress={() => navigation.goBack()}>
        <Ionicons name="caret-back-circle-sharp" color="black" size={40} />
      </TouchableOpacity>
      <Text style={[Design.heading, {marginTop: 10}]}>Privacy Policy :</Text>
      <Text style={Design.subHeading}>
        Last updated: August 30, 2024{'\n'}
        {'\n'}
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.{'\n'}
        {'\n'}
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Privacy Policy Generator.{'\n'}
        {'\n'}
      </Text>

      <Text style={Design.heading}>Interpretation and Definitions</Text>
      <Text style={Design.subHeading}>
        Interpretation{'\n'}
        {'\n'}
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.{'\n'}
        {'\n'}
      </Text>
      <Text style={Design.subHeading}>
        Definitions{'\n'}
        {'\n'}
        For the purposes of this Privacy Policy:{'\n'}
        {'\n'}
        Account means a unique account created for You to access our Service or
        parts of our Service.{'\n'}
        Affiliate means an entity that controls, is controlled by or is under
        common control with a party, where "control" means ownership of 50% or
        more of the shares, equity interest or other securities entitled to vote
        for election of directors or other managing authority.{'\n'}
        Application refers to Grace and Glam, the software program provided by
        the Company.{'\n'}
        Company (referred to as either "the Company", "We", "Us" or "Our" in
        this Agreement) refers to Grace and Glam.{'\n'}
        Country refers to: Pakistan{'\n'}
        Device means any device that can access the Service such as a computer,
        a cellphone or a digital tablet.{'\n'}
        Personal Data is any information that relates to an identified or
        identifiable individual.{'\n'}
        Service refers to the Application.{'\n'}
        Service Provider means any natural or legal person who processes the
        data on behalf of the Company. It refers to third-party companies or
        individuals employed by the Company to facilitate the Service, to
        provide the Service on behalf of the Company, to perform services
        related to the Service or to assist the Company in analyzing how the
        Service is used.{'\n'}
        Usage Data refers to data collected automatically, either generated by
        the use of the Service or from the Service infrastructure itself (for
        example, the duration of a page visit).{'\n'}
        You means the individual accessing or using the Service, or the company,
        or other legal entity on behalf of which such individual is accessing or
        using the Service, as applicable.{'\n'}
        {'\n'}
      </Text>

      <Text style={Design.heading}>
        Collecting and Using Your Personal Data
      </Text>
      <Text style={Design.subHeading}>
        Types of Data Collected{'\n'}
        {'\n'}
        Personal Data{'\n'}
        {'\n'}
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:{'\n'}
        {'\n'}- Usage Data{'\n'}
        Usage Data{'\n'}
        {'\n'}
        Usage Data is collected automatically when using the Service.{'\n'}
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.{'\n'}
        {'\n'}
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.{'\n'}
        {'\n'}
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.{'\n'}
        {'\n'}
        Information Collected while Using the Application{'\n'}
        {'\n'}
        While using Our Application, in order to provide features of Our
        Application, We may collect, with Your prior permission:{'\n'}
        {'\n'}- Pictures and other information from your Device's camera and
        photo library{'\n'}
        We use this information to provide features of Our Service, to improve
        and customize Our Service. The information may be uploaded to the
        Company's servers and/or a Service Provider's server or it may be simply
        stored on Your device.{'\n'}
        {'\n'}
        You can enable or disable access to this information at any time,
        through Your Device settings.{'\n'}
        {'\n'}
      </Text>

      <Text style={Design.heading}>Use of Your Personal Data</Text>
      <Text style={Design.subHeading}>
        The Company may use Personal Data for the following purposes:{'\n'}
        {'\n'}- To provide and maintain our Service, including to monitor the
        usage of our Service.{'\n'}- To manage Your Account: to manage Your
        registration as a user of the Service. The Personal Data You provide can
        give You access to different functionalities of the Service that are
        available to You as a registered user.{'\n'}- For the performance of a
        contract: the development, compliance and undertaking of the purchase
        contract for the products, items or services You have purchased or of
        any other contract with Us through the Service.{'\n'}- To contact You:
        To contact You by email, telephone calls, SMS, or other equivalent forms
        of electronic communication, such as a mobile application's push
        notifications regarding updates or informative communications related to
        the functionalities, products or contracted services, including the
        security updates, when necessary or reasonable for their implementation.
        {'\n'}- To provide You with news, special offers and general information
        about other goods, services and events which we offer that are similar
        to those that you have already purchased or enquired about unless You
        have opted not to receive such information.{'\n'}- To manage Your
        requests: To attend and manage Your requests to Us.{'\n'}- For business
        transfers: We may use Your information to evaluate or conduct a merger,
        divestiture, restructuring, reorganization, dissolution, or other sale
        or transfer of some or all of Our assets, whether as a going concern or
        as part of bankruptcy, liquidation, or similar proceeding, in which
        Personal Data held by Us about our Service users is among the assets
        transferred.{'\n'}- For other purposes: We may use Your information for
        other purposes, such as data analysis, identifying usage trends,
        determining the effectiveness of our promotional campaigns and to
        evaluate and improve our Service, products, services, marketing and your
        experience.{'\n'}
        {'\n'}
        We may share Your personal information in the following situations:
        {'\n'}
        {'\n'}- With Service Providers: We may share Your personal information
        with Service Providers to monitor and analyze the use of our Service, to
        contact You.{'\n'}- For business transfers: We may share or transfer
        Your personal information in connection with, or during negotiations of,
        any merger, sale of Company assets, financing, or acquisition of all or
        a portion of Our business to another company.{'\n'}- With Affiliates: We
        may share Your information with Our affiliates, in which case we will
        require those affiliates to honor this Privacy Policy. Affiliates
        include Our parent company and any other subsidiaries, joint venture
        partners or other companies that We control or that are under common
        control with Us.{'\n'}- With business partners: We may share Your
        information with Our business partners to offer You certain products,
        services or promotions.{'\n'}- With other users: when You share personal
        information or otherwise interact in the public areas with other users,
        such information may be viewed by all users and may be publicly
        distributed outside.{'\n'}- With Your consent: We may disclose Your
        personal information for any other purpose with Your consent.{'\n'}
        {'\n'}
      </Text>

      <Text style={Design.heading}>Retention of Your Personal Data</Text>
      <Text style={Design.subHeading}>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.{'\n'}
        {'\n'}
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.{'\n'}
        {'\n'}
      </Text>

      <Text style={Design.heading}>Transfer of Your Personal Data</Text>
      <Text style={Design.subHeading}>
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ from those of Your jurisdiction.{'\n'}
        {'\n'}
        If You are located outside Pakistan and choose to provide information to
        Us, please note that We transfer the data, including Personal Data, to
        Pakistan and process it there.{'\n'}
        {'\n'}
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.{'\n'}
        {'\n'}
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.{'\n'}
        {'\n'}
      </Text>
    </ScrollView>
  );
};

export default PrivacyPolicy;

const styles = StyleSheet.create({});
